server:
    port: 8080
spring:
    devtools:
        add-properties: false
        livereload:
            enabled: true
    # DB
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/basic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: root
        hikari:
            connectionTimeout: 5000
            validationTimeout: 1000
            maximumPoolSize: 10
mybatis:
    mapper-locations: classpath:/META-INF/mybatis/*/*.xml
    type-aliases-package: com.duplicate.requests.avoid.api.model
logging:
    config: classpath:logback.xml