server:
    port: 8080
spring:
    devtools:
        add-properties: false
        livereload:
            enabled: true
    # DB
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/redundancy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: root
        hikari:
            connectionTimeout: 5000
            validationTimeout: 1000
            maximumPoolSize: 10
mybatis:
    config-location: classpath:/META-INF/mybatis/mybatis-config.xml
    mapper-locations: classpath:/META-INF/mybatis/*/*.xml
    type-aliases-package: com.duplicate.requests.avoid.api.*.dto
logging:
    config: classpath:logback.xml

# Token Info
jwt:
    # 무작위 생성된 UUID
    secret:
        Key: d96607dc-4a0c-4106-95df-4e56ed98d0e1
    # 1 Hour
    access:
        expire: 10800000
    # 1 Day
    refresh:
        expire: 86400000
