
server:
    port: 8080
    servlet:
        jsp:
            init-parameters:
                development: true
spring:
    devtools:
        add-properties: false
        livereload:
            enabled: true 
    # Redis
    redis:
        password: root
        port: 6379
        host: localhost
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
    # DB
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/redundancy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: root
        hikari:
            connectionTimeout: 5000
            validationTimeout: 1000
            maximumPoolSize: 10
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
mybatis:
    config-location: classpath:/META-INF/mybatis/mybatis-config.xml
    mapper-locations: classpath:/META-INF/mybatis/*/*.xml
    type-aliases-package: com.duplicate.requests.avoid.model.dto
logging:
    config: classpath:logback.xml

# Token Info
jwt:
    # 무작위 생성된 UUID
    secret:
        Key: d96607dc-4a0c-4106-95df-4e56ed98d0e1
    # 1 Hour
    access:
        expire: 10800000
    # 1 Day
    refresh:
        expire: 86400000
